version: "3.8"

services:
  parkside-db:
    image: khael618/docker-parkside-db:latest
    container_name: parkside-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: parkside-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@parkside-db:5432/${POSTGRES_DB}
    depends_on:
      - parkside-db
    ports:
      - "8000:8000"

  parkside-client:
    build:
      context: .
      dockerfile: frontend/parkside_client/Dockerfile
    container_name: parkside-client
    depends_on:
      - backend
    ports:
      - "8081:8081"
  parkside-admin:
    build:
      context: .
      dockerfile: frontend/parkside_admin/Dockerfile
    container_name: parkside-admin
    depends_on:
      - backend
    ports:
      - "8082:8082"
volumes:
  db_data:
