"""migracion de prueba

Revision ID: e55ec76b41a8
Revises: 1a31ce608336
Create Date: 2025-03-18 11:18:08.045267

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e55ec76b41a8'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('full_name_user', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_number_card', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_cvc_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_expiration_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
